### ISSUE TITLE
LavaLink works for few days only

### ISSUE THREAD

**Issue by Vaibhav-Naik-1** [DarrenOfficial/lavalink-replit#10]
I forked the github and ran it, it works best without any errors but after 2-4 weeks (sometimes 1-2 weeks ) the lavalink doesn't works it just spams error it doesn't get connected , so i again forked from here and it was working fine, and then again same thing happens. 

THIS LAVALINK works for few days only, please fix it., it has been 2-3 months , now i got fed up, please i request you politely to see whats wrong. You are the best that's why i am using your codes and not of others. 🙂 
![LAVALINK](https://user-images.githubusercontent.com/94748147/174428257-1f56740a-37ee-4ead-a3ba-13e8ef0e3ba7.png)
![NODE](https://user-images.githubusercontent.com/94748147/174428321-c998abb3-d2e5-4d43-a436-9eaca4c6fc9f.png)

**Comment by Kavex** [comment]
Same here, honestly think it's lavalink on replit because it happens when I ran lavalink via bash too

**Comment by DarrenOfficial** [comment]
that is normal. one of the downside of hosting lavalink on replit is that you will see authentication thing alot

**Comment by Vaibhav-Naik-1** [comment]
nope, it is coding error as per me, i fixed it . thanks for replying :)
