### ISSUE TITLE
Keep it on

### ISSUE THREAD

**Issue by Ventispurr** [DarrenOfficial/lavalink-replit#2]
any way to keep it online?

**Comment by DarrenOfficial** [comment]
Yes, make an account here (it’s free) https://www.freshworks.com/website-monitoring/free-uptime-monitoring/ then enter your replit url, then set the ping/monitor duration to 1min. The dashboard will show that the site is offline cause lavalink doesn’t reply to pings, but it should keep pinging your replit and keep it on.

**Comment by Ventispurr** [comment]
alright, so itll keep giving HTTP 401 - Unauthorized but itll keep pinging so itll stay on?

**Comment by DarrenOfficial** [comment]
yeah
