### ISSUE TITLE
could you help me where the problem is?

### ISSUE THREAD

**Issue by GeoXTen** [DarrenOfficial/lavalink-replit#3]
i did exactly same tutorial 
![image](https://user-images.githubusercontent.com/46945867/135380540-bed45d6d-cbe2-4a59-a4d6-bb88f602f88d.png)
![image](https://user-images.githubusercontent.com/46945867/135380594-4a228e16-de5d-427a-93ff-99c20d134533.png)

**Comment by DarrenOfficial** [comment]
You need to remove the `https://` at the host part
