### ISSUE TITLE
Am getting Lavalink: Node Main had an error: Unexpected server response: 400

### ISSUE THREAD

**Issue by johntaxmi** [DarrenOfficial/lavalink-replit#4]
![Screenshot_23](https://user-images.githubusercontent.com/32601829/138872574-809f3f06-96b0-40de-93cf-11af3fd79345.png)
![Screenshot_24](https://user-images.githubusercontent.com/32601829/138872578-dcb7f666-203b-4120-b078-9c5faaa77bda.png)

What am i doing wrong?
I havent changed anything in the lavalink repl

**Comment by DarrenOfficial** [comment]
open your replit url, see if it says error `401` or it says replit is starting up

**Comment by DarrenOfficial** [comment]
open it in your browser

**Comment by johntaxmi** [comment]
![Screenshot_34](https://user-images.githubusercontent.com/32601829/140422221-381dde9e-9091-4435-add6-458a288ba2e9.png)
Am getting that at the repl console. And the repl link does work.

**Comment by iamrahul24** [comment]
> 

i am getting same issue 
 i searched a lot but I cant find a solution.
