### ISSUE TITLE
offline on uptimerobot

### ISSUE THREAD

**Issue by eryycr** [DarrenOfficial/lavalink-replit#6]
i add /version at the end but still don't work, and after the repo stop without a reason! can u help?

**Comment by XenonTheInertG** [comment]
Same issue

**Comment by DarrenOfficial** [comment]
Its because uptimerobots ping it every 5 min, you can use freshwork and set the ping to every 1 minute

**Comment by XenonTheInertG** [comment]
Should i add `/version` also in the config?

**Comment by DarrenOfficial** [comment]
on which config?

**Comment by XenonTheInertG** [comment]
> on which config?

Bot config

**Comment by DarrenOfficial** [comment]
No, you don't need to add /version in the botconfig
