### ISSUE TITLE
It is spamming error

### ISSUE THREAD

**Issue by Vaibhav-Naik-1** [DarrenOfficial/lavalink-replit#9]
https://github.com/DarrenOfficial/lavalink-replit#:~:text=Ignore%20authentication%20fail%20from%20172.X.X.X 
i saw this and you said to ignore it , yes i ignore it if it happens once but it is spamming error and it is not working

**Comment by Vaibhav-Naik-1** [comment]
https://github.com/DarrenOfficial/lavalink-replit#:~:text=Ignore%20authentication%20fail%20from%20172.X.X.X
i saw this and you said to ignore it , yes i ignore it if it happens once but it is spamming error and it doesn't works

**Comment by DarrenOfficial** [comment]
You're most likely ran out of memory/cpu, the solution is to upgrade to replit hacker plan

**Comment by Vaibhav-Naik-1** [comment]
Nope, it is using just 1-5%, and i got to know why is it spamming, if we turn on the repl and then we don't connect to the lavalink for a long time , it spams and then it doesn't gets connected. so the solution is start the lavalink again and connect to it when it is up, it will send only 1 error, which means it is up , and we should connect and once connected it works
